name: linux
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.26'
          - '5.30'
          - '5.36'
    container:
      image: perl:${{ matrix.perl-version }}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Fix ExtUtils::MakeMaker (for Perl 5.16 and 5.18)
        run: cpanm -n App::cpanminus ExtUtils::MakeMaker
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y libmagic-dev ruby-sass
          cpanm -n https://github.com/openSUSE/Spooky-Patterns-XS/archive/1.55.tar.gz
          cpanm -n --installdeps .
          cpanm -n Test::Deep
      - name: Run tests
        env:
          TEST_ONLINE: postgresql://postgres:postgres@postgres:5432/postgres
        run: prove -l t

